name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f3dcef1c512992de2dce668c27add9e4478a477cd4e07bdc1f6823092654a11"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
