name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf843c0e31509dae182a0faeeaa08f6f9c8f8d270782837b120c3dd54f900e4"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
