name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c59e06044e3f73888a19b497b408944e8ac6189e7e54c09d056afffae8377d96"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
