name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a70a4743c7e849c9ea2d38709a3f6b649eb472dc8231270196c8c256743e52e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
