name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a561a37db89729347df78e085cb5c5ba38a9bd044171589e085e679fad2d3499"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
