name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a04e3e34a21aa85e9becedfc07be6f964fd88aaa53eb36443d71c66be2d215f5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
