name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71e3eba2771d3151ef68f4d872902ea3a4496d51634349f745b8931d8ffe613b"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
