name = "VPServerTest"
author = "Dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "094748355ba9ce4094d1c9aec9f6f44003abee957b73a9acb66efa7c8a03f74d"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
